"""add cloud webauthn authentication

Revision ID: 32be2d8da882
Revises: 0a3e1e59c9cf
Create Date: 2026-10-06 22:51:16.249792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32be2d8da882'
down_revision: Union[str, Sequence[str], None] = '0a3e1e59c9cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cloud_passkeys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('credential_id', sa.Text(), nullable=False),
    sa.Column('credential_public_key', sa.Text(), nullable=False),
    sa.Column('sign_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('credential_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('cloud_webauthn_challenges',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('challenge', sa.Text(), nullable=False),
    sa.Column('purpose', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cloud_webauthn_challenges')
    op.drop_table('cloud_passkeys')
    # ### end Alembic commands ###
