apiVersion: 1

datasources:
  - name: Amazon Managed Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: https://aps-workspaces.eu-west-3.amazonaws.com/workspaces/ws-cb298529-e2c9-43c8-b471-d009829fc297
    isDefault: true
    editable: false
    jsonData:
      httpMethod: POST
      sigV4Auth: true
      sigV4AuthType: default
      sigV4Region: eu-west-3
